### PR TITLE
Implement drag-and-drop upload to the paste data set directive

### PR DESCRIPTION
**Pull request by kadamwhite**
dnd upload

I'm working on a UI cue but I wanted to get this up before I left the office

### CODE REVIEW

**Comment by kadamwhite** [comment]
Open question: should dropping a file auto-submit the modal, or do we still want users to click the "add" button? The benefit to the former is ease-of-use; the benefit to the latter is that it encourages users to validate the information uploaded correctly in the text area prior to submitting

**Comment by kadamwhite** [comment]
dnd upload

**Comment by domoritz** [comment]
> Open question: should dropping a file auto-submit the modal, or do we still want users to click the "add" button? The benefit to the former is ease-of-use; the benefit to the latter is that it encourages users to validate the information uploaded correctly in the text area prior to submitting

I'd say no. 

Can we make the drag and drop a bit more obvious? I imagine a drop target either always visible (like a dashed box with gray bold text "Drop CSV/JSON here") or show a drop target when the user drops something. Or at least make the text faster to parse. I personally would never read the text next to the file choose button :-)

**Comment by kadamwhite** [comment]
I'm definitely not a copywriter—I do think some text there would be useful, if you have a better suggestion let me know.

I spent a while trying to get a UI to appear with a drop target when you dragged a file over and it was more complex than I deemed worth pursuing. I can add another static drop-target, though, below the file upload link: would that work?

**Comment by domoritz** [comment]
> I can add another static drop-target, though, below the file upload link: would that work?

That would be great.

**Comment by kadamwhite** [comment]
@domoritz How does this look?

image

Per your feedback I've left it as "dropping a file populates the text areas," and the user manually confirms by clicking the add button. This kept the code much simpler, too.

**Comment by domoritz** [comment]
Looks great. Don't we also support JSON?

**Comment by kadamwhite** [comment]
I wasn't aware JSON was supported, but one of my TODOs today is cross-browser testing, so I'll check that at the same time. Want me to do that as an addendum here, or a separate PR?

**Comment by domoritz** [comment]
Actually, I was wrong. We support JSON for URL dataset but not for pasted dataset. We should add that in a later pr.

**Pull request merged**
