### PR TITLE
Replace data type icons with font awesome icons.

### PR DESCRIPTION
**Pull request by domoritz**
screen shot 2015-10-05 at 15 14 23

### CODE REVIEW

**Comment by domoritz** [comment]
- higher resolution
- remove images
- we can easily switch to another fa icon

I'll delete the icon images form polestar and voyager when we have merged this.

**Comment by domoritz** [comment]
@kanitw @kadamwhite @vlandham Options on this?

**Comment by kanitw** [comment]
I do not like the icon for quantitative fields.

**Comment by domoritz** [comment]
Here is another option. But I prefer the first option because the quantitative data in continuous and # does not indicate that well. 

screen shot 2015-10-06 at 12 52 18

**Comment by kadamwhite** [comment]
Other icons I could see being used to indicate "quantity":

image

These obviously have some conflict of meaning with the fact that _everything_ in Voyager is a chart, but I was thinking that the data-oriented iconography might support the notion of these being numeric, quantitiative fields. Failing that I prefer the **#**.

**Comment by vlandham** [comment]
I think the 'gauge' icon is just a bit too obscure for anyone to connect to what it means. I will spend some time looking at our options to see if there is anything else we could use.

**Comment by domoritz** [comment]
The area chart and signal icons seem like great alternatives. I think I'd vote for the signal icon.

**Comment by domoritz** [comment]
screen shot 2015-10-06 at 13 05 13

**Comment by vlandham** [comment]
+1

**Comment by kadamwhite** [comment]
:+1:

**Comment by kanitw** [comment]
# is consistent with Tableau and Trifacta.

I think the signal (histogram) icon make me thought that I can click it to
see histogram.

**Comment by domoritz** [comment]
screen shot 2015-10-07 at 14 07 54

**Comment by kanitw** [comment]
woohoo -- looks great!

**Pull request merged**
