### PR TITLE
Permit <modal> directive to auto-open based on attribute value

### PR DESCRIPTION
**Pull request by kadamwhite**
In order to support the welcome modal, two approaches could be used: either the controller for the template in which the modal occurs could explicitly `Modals.open('welcome-modal')`, or else the welcome modal could be augmented with an attribute that determines whether the modal will render as open by default instead of closed.

This PR supports the latter interaction as it encapsulates the display-oriented state (whether to show or not) into the directive, rather than depending on a service for display state.

Example usage:

``` html
<!-- template -->
<modal id="welcome-modal" auto-open="showWelcome">
  <h1>Hello! Welcome to Voyager.</h1>
</modal>
```

``` js
// Controller
$scope.showWelcome = isFirstVisitToVoyager();
```

### CODE REVIEW

**Comment by kadamwhite** [comment]
@vlandham if this looks good you can either pull down this branch while you work on Voyager, or else go ahead and merge it so that you're not blocked (cc @domoritz @kanitw for review)

**Comment by kadamwhite** [comment]
Re-set local storage from the dev tools consoleeither with

``` js
angular.element('body').injector().get('localStorageService').set('welcomeModalShown', false);
```

or the nuclear option

``` js
localStorage.clear();
```

**Comment by domoritz** [comment]
Can you make sure that we don't use local storage in the embedded mode?

**Comment by kadamwhite** [comment]
@domoritz Do you mean, "do not show the welcome modal in embedded mode," or "do not use localStorage and instead use cookies or another solution in embedded mode"?

**Comment by kadamwhite** [comment]
Assigning to @vlandham for further work/adaptation/merging; Jim, let me know in Slack if you need anything else on this

**Comment by domoritz** [comment]
> @domoritz Do you mean, "do not show the welcome modal in embedded mode," or "do not use localStorage and instead use cookies or another solution in embedded mode"?

I mean not show the modal in the embedded mode. The problem is that neither cookies nor local storage work that that case.

**Comment by kadamwhite** [comment]
What's an example of how Embedded Mode is detected elsewhere in the app?

**Comment by domoritz** [comment]
For example https://github.com/vega/voyager/blob/master/src/app/main/main.controller.js#L28

**Comment by kadamwhite** [comment]
@vlandham I just force-pushed a rebased version of this (moved it on top of the latest master): you'll probably need to

``` bash
git fetch
git reset --hard origin/kaw/allow-modal-to-auto-open-based-on-attribute
```

or else blow away your local branch and re-checkout if you'd cloned this locally before

**Comment by kadamwhite** [comment]
@domoritz thanks for the clarification.

@vlandham, my proposal in light of Dominik's point—and if you're sufficiently far down the path with vega/voyager#199 that it doesn't make sense to change now, that's fine, I just want to make sure it's documented—is I think the welcomeModal functionality should probably be moved into Voyager and Polestar, instead of being shared in a new directive here. This should make the hierarchy easier (instead of a `<voyager-welcome-modal>` inside a `<welcome-modal>`, you just have a `<welcome-modal>` that is voyager-specific), and it will also enable both the localStorage flag _and_ the embedded flag to be taken into account when determining whether to open the popup.

Let's chat tomorrow, I don't want to step on your toes if you did more work on this after we spoke today

**Comment by vlandham** [comment]
I think that would be completely fine. I think most of the functionality is
already in voyager - so i don't expect moving the local storage stuff over
would be too difficult.

**Comment by kadamwhite** [comment]
Taking this over to refactor this and vega/voyager#199

**Comment by kadamwhite** [comment]
This has been updated: the welcome modal has been moved to Voyager

**Pull request merged**
