### PR TITLE
adding priority queue for render queue in vlplot

### PR DESCRIPTION
**Pull request by kanitw**
**Please merge #12 first**

Adding heap for render queue in vlplot
addressing https://github.com/uwdata/voyager/issues/135

### CODE REVIEW

**Comment by arvind** [comment]
Hmm, so Vega 2 uses a priority queue as well, and used to use `js-priority-queue`but it gave me some bugs (can't remember exactly what they were). I since switched it over to `heap`: https://www.npmjs.com/package/heap which I've found to be more reliable. But if we're using it across our tool stack, maybe we should build our own and put it in `datalib` (`heap` is pretty concise and well written, but its in CoffeeScript...)? /cc @jheer

**Comment by domoritz** [comment]
@kanitw should we use heap? Or stay with js-priority-queue?

**Comment by kanitw** [comment]
@domoritz  Okay.  I have updated vlui to use heap — but due to complication in merges, I just pushed the change to #15.   Please merge #15 directly instead.

**Comment by kanitw** [comment]
Note:   `heap` also has many downloads on `npm` and somewhat more stars on github although that might not be mostly due to naming rather than quality.

**Pull request closed without merging**
