### PR TITLE
Make "load" data takes only one line

### PR DESCRIPTION
**Pull request by kanitw**
(Planned future modification is noted in #113)

### CODE REVIEW

**Comment by kadamwhite** [comment]
This doesn't look great to me on my screen:

image

What about moving the entire data load item down below the "current data" header:
image

Or restoring it to "Data" or changing it to "Dataset" instead of "Current Data"?
image

**Comment by vlandham** [comment]
Yeah - i was trying to better indicate to the user with the word 'current' that it was what they were looking at - at the time (as 'Cars' isn't all that intuitively a dataset until you understand it as such...). Also this makes 'Load' ambiguous.

**Comment by kanitw** [comment]
Yeah, I think we need some more work here to make thing sensible, but in one line. 

In my pending WIP https://github.com/vega/voyager/pull/201, I change this back to data. 

data_voyager

**Comment by vlandham** [comment]
Ok. I'd still vote that describing this is the current data, and providing the option to "load your data" is more important then smashing them into one line

**Pull request merged**
