### PR TITLE
Change default time function to year.

### PR DESCRIPTION
**Pull request by domoritz**
As proposed by @jheer

### CODE REVIEW

**Comment by kanitw** [comment]
I thought we gonna infer correct time unit?

**Comment by domoritz** [comment]
I don't remember that we decided that. How are we going to decide the right time unit? I can think of cases where multiple things make sense.

**Comment by kanitw** [comment]
Most significant unit like you proposed in the vega-lite repo makes sense.  But I think the inference stuff should be done at vlui level

**Comment by domoritz** [comment]
These are two separate issues. And yes, any inference should be done in vl-ui. What I argue is that we cannot make a smart inference.

**Comment by kanitw** [comment]
> What I argue is that we cannot make a smart inference.

Well, something like this?
- if all the values spans multiple year -> then use `year`
- if all the values spans multiple months in one year -> then use `month`.  
- if all the values spans multiple days in one month -> then use `day`
- if all the values spans multiple hours in one day -> then use `hour-minute`

This isn’t perfect but at least it avoids bad default.

**Comment by domoritz** [comment]
> if all the values spans multiple year -> then use year

What if I want to know the average per month over multiple years. I din't think there is a preference for either year or month.

> if all the values spans multiple months in one year -> then use month.

Or aggregate all data for a year. Or aggregate by quarter? Again, no clear preference imho. 

> if all the values spans multiple days in one month -> then use day

Or month? Or hour? 

> if all the values spans multiple hours in one day -> then use hour-minute

I can see this being useful.

I see that good defaults can help. I can implement these suggestions from above but wonder whether it is  worth at this point.

**Comment by kanitw** [comment]
> What if I want to know the average per month over multiple years. I din't think there is a preference for either year or month.

That's fine.  User can override default.

> > if all the values spans multiple months in one year -> then use month.
> > Or aggregate all data for a year. Or aggregate by quarter? Again, no clear preference imho.

I don't know what you mean aggregate all data for a year when the data spans only one year.  Aggregating like that equals do adding nothing.  I agree that people might want quarter so month isn't always correct -- but it is better than showing year when year doesn't matter. 

> > if all the values spans multiple days in one month -> then use day
> > Or month? Or hour?

showing just the month seems weird here...
...

I'll merge `year` for now since we have the issue logged at https://github.com/vega/vega-lite-ui/issues/47.

**Comment by domoritz** [comment]
Great. I moved the important bits.

**Pull request merged**
