### PR TITLE
Move list of loaded datasets to a dataset modal tab

### PR DESCRIPTION
**Pull request by kadamwhite**
See #113: this begins the work of moving the dataset list to a tab.

image

### CODE REVIEW

**Comment by kadamwhite** [comment]
Also currently supports displaying user-loaded data:
image

**Comment by kanitw** [comment]
Adding font awesome's `database` icon pasted_image_10_15_15__3_10_pm both here and in front of dataset name in the main screen might help suggest that these are dataset names.

(Inspired by Tableau: tableau_-_sales__read-only_)

**Comment by domoritz** [comment]
Instead of buttons, can we just use the dropdown? Or even better, move the samples to a new tab into a scrollable list.

**Comment by kadamwhite** [comment]
@domoritz I like having all of the loaded datasets on one tab, but there's _definitely_ some UI improvements needed :) Working on that now, I'll see whether the dropdown feels more or less intuitive.

**Comment by kadamwhite** [comment]
image
@kanitw @domoritz Thoughts on how it's evolving?

**Comment by kadamwhite** [comment]
Collapses to one column on small screens:
image

**Comment by kanitw** [comment]
I like one column better.  A few comments:

1)  should sample dataset be in the same tab as "change dataset"?   Maybe it should be in separate tabs

2) I also think we should pick one between "change dataset" or "switch dataset" and just use the same text both in the tab and header

**Comment by kadamwhite** [comment]
@kanitw One column feels too "long" to me, so while I will absolutely change it if you feel strongly, I think two-columns on wide screens makes the list more scannable and makes the descriptions readable without artificially wrapping the text.

In a comment above I remarked to @domoritz that I prefer having user-loaded and sample data in one pane: this pane says "this is all of the current-accessible data", and all other panes are dedicated to loading data. Splitting it into two panes I feel would bury the sample data after you've loaded your own data. I feel more strongly about this than about the column arrangement; ideally we'd have time to user-test this but in the interest of completing the work today I would like to ask your pardon, and ask to keep going with the one-tab approach.

Thoughts?

**Comment by kanitw** [comment]
I think what you said make sense, so feel free to go ahead with two columns. 

That said, in the two columns screenshot above, there is not distinction between "loaded" datasets and "example" datasets.  I think the distinction between the two is quite important, otherwise it might be confusing for some users.

**Comment by kadamwhite** [comment]
@kanitw that's an excellent point, let me address that—I'll have another screenshot shortly

**Comment by kadamwhite** [comment]
@kanitw @domoritz How about this:

image

image

**Comment by kanitw** [comment]
Nice!  

Final small nit:  maybe add some background color to just the selected one to enhance clarity?

**Comment by kadamwhite** [comment]
@kanitw Good suggestion! I've settled on this for now; I'm going to move on to another issue for the time being, but this does make it much more evident which dataset is selected

image

**Comment by kanitw** [comment]
I like this.  Not sure if this is ready to merged, but if it is, feel free to do so :)

**Comment by kadamwhite** [comment]
I was just doing some final checks, should be good to go! Merging now.

**Comment by kanitw** [comment]
:tada:

**Pull request merged**
